POST http://192.168.1.20:5000/api/register
content-Type: application/json

{
    "phone_number": "03361234568", 
    "password": "Something12345",
    "first_name":"Sarfaraz",
    "last_name":"Jaffery"
}

###
POST http://localhost:5000/api/login
content-Type: application/json

{
    "phone_number": "03361234568", 
    "password": "Something12345"
}

###
Get http://localhost:5000/api/profile/fullname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

###
Get http://localhost:5000/api/login/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTcwMTY3OSwiZXhwIjoxNjk1NzAyMDM5fQ.fnvddDYpCOElQXgdQNrCTX7fzoxmFzLGhMZhAeezSfw

###
GET http://localhost:5000/api/profile/checkcnic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

###
GET http://localhost:5000/api/profile/userHomeAddress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

###
POST http://localhost:5000/api/profile/userHomeAddress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

{
    "address": "C 109 Rafa e aam Society Malir Halt",
    "city": "Karachi",
    "province": "Sindh",
    "country": "Pakistan"
}

###
GET http://localhost:5000/api/profile/markets

###
POST http://localhost:5000/api/profile/usermarkets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

{
    "market_name": "Hyderabad, New Sabzi Mandi"
}

###
GET http://localhost:5000/api/profile/usermarkets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

###
GET http://localhost:5000/api/profile/userFarms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

###
POST http://localhost:5000/api/profile/userFarms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

{
    "area": 20,
    "address": "Near Hotel Karwana",
    "city": "Gharo",
    "province": "Sindh",
    "country": "Pakistan"
}

###
PUT http://localhost:5000/api/profile/userFarms/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8

{
    "area": 16,
    "address": "Near Hotel Karwana",
    "city": "Gharo",
    "province": "Sindh",
    "country": "Pakistan"
}

###
DELETE http://localhost:5000/api/profile/userFarms/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIwMzM2MTIzNDU2OCIsImlhdCI6MTY5NTgyODgzMywiZXhwIjoxNjk1OTE1MjMzfQ.HQ4I2yg28--XvsRSWb1GmAxScQ5T6IaSQptq-2deOP8


