POST http://localhost:5000/api/register
Content-Type: application/json

{
    "phone_number": "+923461234567", 
    "password": "Something12345",
    "first_name":"Sarfaraz",
    "last_name":"Jaffery"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "phone_number": "+923461234567", 
    "password": "Something12345"
}