POST http://192.168.1.20:5000/api/register
content-Type: application/json

{
    "phone_number": "+92336123456789", 
    "password": "Something12345",
    "first_name":"Sarfaraz",
    "last_name":"Jaffery"
}

###
POST http://localhost:5000/api/login
content-Type: application/json

{
    "phone_number": "+923471234567", 
    "password": "Something12345"
}